### ISSUE TITLE
dice bag average is incorrectly floored

### ISSUE THREAD

**Issue by HeladoDeBrownie** [TrashMonks/hagadias#31]
the average of a dice roll needs to be able to be a fractional number in order to allow two dice distributions to be accurately compared. the `int` call needs to be removed (and it needs to be tested working correctly with cryptogull)

**Comment by egocarib** [comment]
This function does get used downstream in some of the wiki calculations, where I believe we are relying on the result being floored in order for things to be consistent with certain parts of the wiki. For example, it is used to calculate ego bonus for mutations.

I don't recall the exact implementation details, but I know that this was intentionally designed this way and I believe it has some precarious links to the wiki stat extraction.

**Comment by HeladoDeBrownie** [comment]
thanks for the info! i will take a look around to make sure

**Comment by HeladoDeBrownie** [comment]
i checked and that location already has `int` applied anyway
