### ISSUE TITLE
References font file that is not included

### ISSUE THREAD

**Issue by syntaxaire** [TrashMonks/hagadias#55]
hagadias commit 70aa4635ce7cc5f49254de0321ab8b733f25b1e0 references a TTF file that was included in a matching commit to a different repository, trashmonks/qud-wiki@876d41c7a66833f9d10bf47332c70f3821020421. As a result, using hagadias standalone can yield

![error screenshot](https://i.imgur.com/WEIKpGe.png)

**Comment by egocarib** [comment]
Probably we should just fail gracefully if the files are present, logging an informational warning. However the "fail gracefully" part is a bit tricky, might require sitting down and thinking carefully about the places that use this file

**Comment by syntaxaire** [comment]
Resolved in hagadias with 0823e193005170ae9239140355e7c0bbf5dfeab8.
